[package]
name = "teleop-record-replay"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.5", features = ["derive"] } # Updated clap version for compatibility
log = "0.4"
env_logger = "0.11"
