# Configuration for the Teleop-Record-Replay application

[app]
# The terminal emulator to use. Examples: "xterm", "gnome-terminal", "konsole".
terminal = "konsole"

# Path to the base of the conda installation (e.g., anaconda3, miniconda3).
# This is needed to correctly initialize conda in the new shell.
# IMPORTANT: The user on the new machine MUST update this path.
conda_path = "/home/denis/miniconda3" # or /home/user/anaconda3

[commands]
# We use `conda run` to reliably execute commands within the 'lerobot' environment.
# This is the recommended approach for scripting with conda.
# It handles environment activation internally.
# IMPORTANT: Make sure your lerobot project is at '/home/$USER/lerobot' or update the path.
working_directory = "/home/$USER/lerobot"

# Specific command for teleoperation
teleoperation = """
conda run -n lerobot lerobot-teleoperate \
    --robot.type=so101_follower \
    --robot.port=/dev/ttyACM0 \     
    --robot.id=my_awesome_follower_arm \
    --teleop.type=so101_leader \
    --teleop.port=/dev/ttyACM1 \
    --teleop.id=my_awesome_leader_arm \
    --display_data=false
"""
            


# Specific command for recording
record = """
rm -r /home/denis/.cache/huggingface/lerobot/robohouse/demo && conda run -n lerobot lerobot-record \
--robot.type=so101_follower \
--robot.port=/dev/ttyACM0 \     
--robot.id=my_awesome_follower_arm \
--teleop.type=so101_leader \
--teleop.port=/dev/ttyACM1 \
--teleop.id=my_awesome_leader_arm \
--display_data=false \
--dataset.repo_id=robohouse/demo \
--dataset.single_task="demo" \
--dataset.push_to_hub=False
"""

# Specific command for replaying
replay = """
conda run -n lerobot lerobot-replay \
--robot.type=so101_follower \
--robot.port=/dev/ttyACM0 \     
--robot.id=my_awesome_follower_arm \
--dataset.repo_id=robohouse/demo \
--dataset.episode=0
"""